
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hypr.land/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2

# Universal max
# monitor = , preferred, auto, 1


# High Res 1 monitor - laptop
# monitor = eDP-1, preferred, auto, 2

# 1920x1080 laptop 
# monitor = eDP-1, 1920x1200@120, auto, 1

# CSUF Laptop - Plugged in Monitor setup
monitor = eDP-1, preferred, 0x0, 2
monitor = , 3840x2160@60, 0x-1080, 2
# We use -1080 because we account for x2 Zoom.  
# 2160 /2 == 1080, and - makes it go up
