##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example #windowrulee v1
# #windowrulee = float, ^(kitty)$

# Example #windowrulee v2
# #windowrule = float,class:^(kitty)$,title:^(kitty)$

# This all pertains to some stupid windows settings for Godot

windowrule = match:class = ^(Godot)$, size 800 800, match:title = ^(Project Settings.*)$
#windowrule = size 800 800, class:^(Godot)$, title:^(Project Settings.*)$
#windowrule = center, class:^(Godot)$, title:^(Project Settings.*)$
#windowrule = size 1000 800, class:^(Godot)$, title:^(Save Scene As.*)$
#windowrule = center, class:^(Godot)$, title:^(Save Scene As.*)$
#windowrule = size 1000 800, class:^(Godot)$, title:^(.*Location.*)$
#windowrule = center, class:^(Godot)$, title:^(.*Location.*)$
#windowrule = size 1000 800, class:^(Godot)$, title:^(.*Create.*)$
#windowrule = center, class:^(Godot)$, title:^(.*Create.*)$
#windowrule = size 1000 800, class:^(Godot)$, title:^(.*Change.*)$
#windowrule = center, class:^(Godot)$, title:^(.*Change.*)$
#windowrule = size 1000 800, class:^(Godot)$, title:^(.*Open.*)$
#windowrule = center, class:^(Godot)$, title:^(.*Open.*)$
#windowrule = size 800 600, class:^(Godot)$, title:^(.*Dependencies.*)$
#windowrule = center, class:^(Godot)$, title:^(.*Dependencies.*)$

# Floating Windows 
#windowrule = float, center, title:^(Volume Control)$ # For pavucontrol to be a floating window
#windowrule = size 800 600, title:^(Volume Control)$ # For pavucontrol to be a floating window
#windowrule = float, center, title:^(Bluetooth Devices)$ # For blueman-manager to be a floating window
#windowrule = size 800 600, title:^(Bluetooth Devices)$ # For blueman-manager to be a floating window

#windowrule = float, class:^(Godot)$